### ISSUE TITLE
過去の月を選択すると404 not found

### ISSUE THREAD

**Issue by atani** [tosite0345/nicocale.php#120]
![error](https://user-images.githubusercontent.com/76104/60404477-5efd0600-9be4-11e9-9af6-5dfa12ac9374.gif)

過去の月を選択すると 404 not found になるようです。

**Comment by tosite0345** [comment]
|ユーザー一覧|ユーザー個別|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24952964/62470481-7deb4b00-b7d5-11e9-9559-1c9916cecb5d.png) | ![image](https://user-images.githubusercontent.com/24952964/62470512-90658480-b7d5-11e9-9674-add0bb613bbc.png) |

**Comment by tosite0345** [comment]
初期状態で与えられるデータは変わらなさそう。

**Comment by tosite0345** [comment]
`this.YearAndMonth` などというパラメータがなかった。原因わかったので修正入れる。
